version: "0.2"
ignorePaths:
  - .devcontainer
  - .vscode
  - .gitignore
  - cspell.config.yaml
  - .trunk
  - go.mod
  - go.sum
  - vendor
dictionaryDefinitions: []
dictionaries: []
words:
  - apimachinery
  - backube
  - clientcmd
  - clientset
  - kubeconfig
  - logrus
  - metav
  - oidc
  - replicationsource
  - replicationsources
  - Rojikku
  - runtimes
  - sirupsen
  - unmarshaled
  - unshallow
  - volsync
  - woodpeckerci
ignoreWords: []
import: []
