version: "0.2"
ignorePaths:
  - .devcontainer
  - .vscode
  - .gitignore
  - cspell.config.yaml
dictionaryDefinitions: []
dictionaries: []
words:
  - apimachinery
  - clientcmd
  - clientset
  - kubeconfig
  - metav
  - oidc
  - unshallow
  - volsync
ignoreWords: []
import: []
